# -*- coding: utf-8 -*-
# gen_icons.py — pulls the Blender UI icons the tool uses (release/datafiles/icons_svg, GPL-2.0-or-later)
# and writes icons_blender.h: {name, svg} pairs, rasterised at run time by nanosvg (main.cpp, drawIcon()).
# Swapping the set for another licence = editing ICONS below and re-running.  python gen_icons.py
import io, re, sys, urllib.request

BASE = "https://raw.githubusercontent.com/blender/blender/main/release/datafiles/icons_svg/"
# enum name → Blender icon file (without .svg)
ICONS = [
    ("BI_OUTLINER",   "outliner"),           # Проблемы (the table)
    ("BI_UNLINKED",   "unlinked"),           # Лишнее (files nobody references)
    ("BI_WORLD",      "world"),              # Карта
    ("BI_VIEW3D",     "view3d"),             # 3D
    ("BI_HELP",       "help"),               # Справочник кодов
    ("BI_QUESTION",   "question"),           # Справка
    ("BI_WINDOW",     "window"),             # панель справа
    ("BI_PREFS",      "preferences"),        # Настройки
    ("BI_SUN",        "light_sun"),          # день
    ("BI_FOLDER",     "file_folder"),        # категория в дереве
    ("BI_FILE",       "file_text"),          # файл в дереве
    ("BI_TRI_RIGHT",  "disclosure_tri_right"),
    ("BI_TRI_DOWN",   "disclosure_tri_down"),
    ("BI_ZOOM",       "viewzoom"),           # поиск
]

def fetch(name):
    with urllib.request.urlopen(BASE + name + ".svg") as r:
        return r.read().decode("utf-8")

def minify(svg):
    svg = re.sub(r"<sodipodi:namedview.*?</sodipodi:namedview>", "", svg, flags=re.S)
    svg = re.sub(r'\s+xmlns:(inkscape|sodipodi)="[^"]*"', "", svg)
    svg = re.sub(r"\s+", " ", svg).strip()
    return svg

def cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

out = io.StringIO()
out.write("// generated by gen_icons.py — Blender UI icons (blender/blender release/datafiles/icons_svg), GPL-2.0-or-later.\n")
out.write("// Rasterised at run time by nanosvg; see drawIcon() in main.cpp. Do not edit by hand.\n")
out.write("#pragma once\n\nenum { " + ", ".join(e for e, _ in ICONS) + ", BI_NUM };\n\n")
out.write("static const struct { const char *name; const char *svg; } BLENDER_ICONS[BI_NUM] = {\n")
for enum, name in ICONS:
    svg = minify(fetch(name))
    out.write("\t{ %s, %s },\n" % (cstr(name), cstr(svg)))
    print(enum, name, len(svg))
out.write("};\n")
io.open("icons_blender.h", "w", encoding="utf-8", newline="\n").write(out.getvalue())
print("icons_blender.h written")
