# The pixel / retro faces of the «аркада» look → src/font_pixel.h (all six are OFL, all carry the full
# Cyrillic alphabet — that is why Press Start 2P, VT323, Silkscreen, Micro 5, Doto, Jersey and the rest of
# the usual pixel fonts are not here: they are Latin only and the Russian UI would come out empty).
# Variable fonts are instanced to static weights first (stb_truetype inside ImGui ignores the axes), then
# every face is subset to what the UI shows (Latin, Latin-1, Cyrillic, punctuation, arrows).
#   Handjet        — pixel grid, ELGR 1 / ELSH 2 (square elements); weights 400 / 700
#   Tiny5          — a true 5 px bitmap face; one weight
#   Pixelify Sans  — rounder pixels; lacks О, П, І (mapped onto Latin O, Greek Pi, Latin I) and its С is
#                    nearly identical to О, so it reads best in Latin
#   Rubik Mono One — wide arcade-cabinet display face; one weight
#   Unbounded      — techno grotesque, weights 400 / 700
#   Stalinist One  — constructivist square caps; one weight
import io, os
from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

SP = os.path.dirname(os.path.abspath(__file__))
SRC = r"C:\Users\q3726\AppData\Local\Temp\claude\f--GitHub-INU-Check-GTA\5de09b3e-8ceb-47f2-95f2-ea46a101c589\scratchpad"
OUT = os.path.join(SP, "font_pixel.h")

UNICODES = (list(range(0x20, 0x7F)) + list(range(0xA0, 0x100)) + list(range(0x400, 0x460))
            + list(range(0x2000, 0x2070)) + list(range(0x2190, 0x21B0)) + [0x2116, 0x2122, 0x2713, 0x2717, 0x00D7])


def build(src, axes, fix_cyr, dst):
    f = TTFont(os.path.join(SRC, src))
    if axes:
        instancer.instantiateVariableFont(f, axes, inplace=True)
    if fix_cyr:
        cm = {}
        for t in f['cmap'].tables:
            cm.update(t.cmap)
        for t in f['cmap'].tables:
            if t.isUnicode():
                t.cmap[0x41E] = cm[0x4F]    # О ← O
                t.cmap[0x41F] = cm[0x3A0]   # П ← Pi
                t.cmap[0x406] = cm[0x49]    # І ← I
    opts = subset.Options()
    opts.layout_features = ['kern', 'liga', 'calt']
    opts.name_IDs = ['*']
    opts.notdef_outline = True
    opts.hinting = False
    s = subset.Subsetter(opts)
    s.populate(unicodes=UNICODES)
    s.subset(f)
    p = os.path.join(SRC, dst)
    f.save(p)
    return open(p, 'rb').read()


FACES = [
    # var name, regular (src, axes, fix), bold (src, axes, fix) — bold None = reuse the regular data
    ('pix1', 'handjet.ttf', {'wght': 400, 'ELGR': 1, 'ELSH': 2}, False, 'handjet.ttf', {'wght': 700, 'ELGR': 1, 'ELSH': 2}, False),
    ('pix2', 'tiny5.ttf', None, False, None, None, False),
    ('pix3', 'pixelify.ttf', {'wght': 400}, True, 'pixelify.ttf', {'wght': 700}, True),
    ('pix4', 'rubikmonoone.ttf', None, False, None, None, False),
    ('pix5', 'unbounded.ttf', {'wght': 400}, False, 'unbounded.ttf', {'wght': 700}, False),
    ('pix6', 'stalinistone.ttf', None, False, None, None, False),
]

blobs = []
for name, rsrc, raxes, rfix, bsrc, baxes, bfix in FACES:
    reg = build(rsrc, raxes, rfix, name + '_r_sub.ttf')
    bold = build(bsrc, baxes, bfix, name + '_b_sub.ttf') if bsrc else None
    blobs.append((name, reg, bold))
    print(name, rsrc, len(reg), 'bold', len(bold) if bold else '(same)')


def emit(f, name, data):
    f.write('static const unsigned int %s_size = %d;\n' % (name, len(data)))
    f.write('static const unsigned char %s_data[%d] = {\n' % (name, len(data)))
    for i in range(0, len(data), 24):
        f.write('\t' + ','.join(str(b) for b in data[i:i + 24]) + ',\n')
    f.write('};\n')


LICENSES = [('Handjet', 'OFL_handjet.txt'), ('Tiny5', 'OFL_tiny5.txt'), ('Pixelify Sans', 'OFL_pixelify.txt'),
            ('Rubik Mono One', 'OFL_rubikmonoone.txt'), ('Unbounded', 'OFL_unbounded.txt'), ('Stalinist One', 'OFL_stalinistone.txt')]

with io.open(OUT, 'w', encoding='utf-8', newline='\n') as f:
    f.write('// The pixel / retro faces of the «аркада» look (Настройки → «пиксельный шрифт»), all SIL Open Font\n')
    f.write('// License 1.1 and all with the full Cyrillic alphabet: Handjet, Tiny5, Pixelify Sans, Rubik Mono One,\n')
    f.write('// Unbounded, Stalinist One. Variable faces are instanced to static weights, every face subset to\n')
    f.write('// Latin / Latin-1 / Cyrillic / punctuation / arrows. Generated by src/gen_font_pixel.py.\n')
    f.write('// Pixelify Sans lacks О, П and І — they are mapped onto the identical Latin O, Greek Pi and Latin I.\n//\n')
    for tag, path in LICENSES:
        f.write('// --- %s ---\n' % tag)
        for line in io.open(os.path.join(SRC, path), encoding='utf-8').read().strip().splitlines():
            f.write('// ' + line + '\n' if line.strip() else '//\n')
        f.write('//\n')
    f.write('#ifndef GTACHECK_FONT_PIXEL_H\n#define GTACHECK_FONT_PIXEL_H\n')
    for name, reg, bold in blobs:
        emit(f, name + '_font', reg)
        if bold is not None:
            emit(f, name + 'b_font', bold)
        else:
            f.write('static const unsigned int %sb_font_size = %s_font_size;\t// one weight only: bold reuses it\n' % (name, name))
            f.write('#define %sb_font_data %s_font_data\n' % (name, name))
    f.write('#endif\n')
print('written', OUT, os.path.getsize(OUT))
