"""Regenerates vanilla_<game>.h from a --baseline-dump of a stock install.

    gtacheck.exe --cli "D:\\Grand Theft Auto San Andreas" --no-modloader --info --baseline-dump vanilla_dump.txt
    python make_baseline.py vanilla_dump.txt            # SA 1.0 US  -> vanilla_sa.h
    python make_baseline.py dump_iii.txt iii            # GTA III 1.0 -> vanilla_iii.h
    python make_baseline.py dump_vc.txt vc              # VC 1.0     -> vanilla_vc.h

Re-run after changing any message text: the baseline matches messages verbatim.
"""
import sys, io, os

EXCLUDE = {"AUD-27", "AUD-28"}   # stream-pack findings depend on the install (empty packs), never baseline them

src = sys.argv[1] if len(sys.argv) > 1 else "vanilla_dump.txt"
game = (sys.argv[2] if len(sys.argv) > 2 else "sa").lower()
assert game in ("sa", "iii", "vc")
NAME = {"sa": "SA 1.0 US", "iii": "GTA III 1.0", "vc": "Vice City 1.0"}[game]
out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "vanilla_%s.h" % game)
keys = set()
for line in io.open(src, encoding="utf-8"):
    parts = line.split()
    if len(parts) < 2 or parts[1] in EXCLUDE:
        continue
    keys.add(int(parts[0], 16))
keys = sorted(keys)
G = game.upper()
with io.open(out, "w", encoding="utf-8", newline="\n") as f:
    f.write("// gtacheck — vanilla baseline (generated by make_baseline.py from `gtacheck --cli <vanilla %s> --no-modloader --info --baseline-dump`).\n" % NAME)
    f.write("// Sorted FNV-1a hashes of \"code|file name|object|message\" for every issue stock %s produces.\n" % NAME)
    f.write("#ifndef GTACHECK_VANILLA_%s_H\n#define GTACHECK_VANILLA_%s_H\n" % (G, G))
    f.write("static const uint64_t VANILLA_%s[] = {\n" % G)
    for i in range(0, len(keys), 6):
        f.write("\t" + ",".join("0x%016xull" % k for k in keys[i:i + 6]) + ",\n")
    f.write("};\nstatic const size_t VANILLA_%s_COUNT = %d;\n#endif\n" % (G, len(keys)))
print("vanilla_%s.h:" % game, len(keys), "keys")
