"""gtacheck localisation helper.

    python make_lang.py sync            # scan *.cpp for Russian literals, update lang.tsv (new keys get empty en/es),
                                        # write lang_keys.txt (numbered keys needing translation) and lang_data.h
    python make_lang.py merge FILE LANG # merge "N<TAB>translation" lines (numbers from lang_keys.txt) into lang.tsv column LANG (en|es)
    python make_lang.py build           # lang.tsv -> lang_data.h only

lang.tsv: ru<TAB>en<TAB>es per line, "\\n" / "\\t" / "\\\\" escaped.  Keys are the runtime form of the
source literals (C escapes decoded, adjacent literals joined); printf specs (%d, %s, %.1f, %%…) must
stay in the same order in every translation — the matcher re-inserts the captured values by position.
"""
import sys, io, os, re, glob

HERE = os.path.dirname(os.path.abspath(__file__))
TSV = os.path.join(HERE, 'lang.tsv')
KEYS = os.path.join(HERE, 'lang_keys.txt')
OUT = os.path.join(HERE, 'lang_data.h')
CYR = re.compile(r'[\u0400-\u04FF]')

def strip_comments(src):
    out = []; i = 0; n = len(src); instr = False
    while i < n:
        c = src[i]
        if instr:
            out.append(c)
            if c == '\\' and i + 1 < n: out.append(src[i + 1]); i += 2; continue
            if c == '"': instr = False
            i += 1; continue
        if c == '"': instr = True; out.append(c); i += 1; continue
        if src.startswith('//', i):
            j = src.find('\n', i); i = n if j < 0 else j; continue
        if src.startswith('/*', i):
            j = src.find('*/', i + 2); i = n if j < 0 else j + 2; out.append(' '); continue
        out.append(c); i += 1
    return ''.join(out)

def unescape(lit):
    out = []; i = 0; n = len(lit)
    while i < n:
        c = lit[i]
        if c == '\\' and i + 1 < n:
            d = lit[i + 1]
            if d == 'n': out.append('\n'); i += 2; continue
            if d == 't': out.append('\t'); i += 2; continue
            if d == 'r': out.append('\r'); i += 2; continue
            if d == '0': out.append('\0'); i += 2; continue
            if d == 'x':
                m = re.match(r'[0-9A-Fa-f]{1,2}', lit[i + 2:]); h = m.group(0) if m else '0'
                out.append(chr(int(h, 16))); i += 2 + len(h); continue
            out.append(d); i += 2; continue
        out.append(c); i += 1
    return ''.join(out)

LIT_RUN = re.compile(r'(?<![A-Za-z0-9_])L?"(?:[^"\\\n]|\\.)*"(?:\s*"(?:[^"\\\n]|\\.)*")*')

def extract(files):
    keys = []
    seen = set()
    for f in files:
        src = strip_comments(io.open(f, encoding='utf-8').read())
        for m in LIT_RUN.finditer(src):
            run = m.group(0)
            if run.startswith('L"'): continue
            # skip debug prints
            ls = src.rfind('\n', 0, m.start()) + 1
            line = src[ls:src.find('\n', m.start())]
            if 'fprintf(stderr' in line or 'GTACHECK_TRACE' in line: continue
            parts = re.findall(r'"((?:[^"\\\n]|\\.)*)"', run)
            key = unescape(''.join(parts))
            if not CYR.search(key) or key in seen: continue
            seen.add(key); keys.append(key)
    return keys

def esc_tsv(s): return s.replace('\\', '\\\\').replace('\n', '\\n').replace('\t', '\\t')
def unesc_tsv(s):
    out = []; i = 0
    while i < len(s):
        if s[i] == '\\' and i + 1 < len(s):
            d = s[i + 1]; out.append({'n': '\n', 't': '\t', '\\': '\\'}.get(d, d)); i += 2
        else: out.append(s[i]); i += 1
    return ''.join(out)

def read_tsv():
    rows = {}; order = []
    if os.path.exists(TSV):
        for line in io.open(TSV, encoding='utf-8'):
            line = line.rstrip('\n')
            if not line: continue
            cols = line.split('\t')
            while len(cols) < 3: cols.append('')
            ru = unesc_tsv(cols[0])
            rows[ru] = [unesc_tsv(cols[1]), unesc_tsv(cols[2])]; order.append(ru)
    return rows, order

def write_tsv(order, rows):
    with io.open(TSV, 'w', encoding='utf-8', newline='\n') as f:
        for ru in order:
            en, es = rows[ru]
            f.write(esc_tsv(ru) + '\t' + esc_tsv(en) + '\t' + esc_tsv(es) + '\n')

def cstr(s):
    out = ['"']
    for ch in s:
        if ch == '"': out.append('\\"')
        elif ch == '\\': out.append('\\\\')
        elif ch == '\n': out.append('\\n')
        elif ch == '\t': out.append('\\t')
        elif ch == '\r': out.append('\\r')
        elif ch == '\0': out.append('\\0')
        else: out.append(ch)
    out.append('"')
    return ''.join(out)

def build(order, rows):
    with io.open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('// gtacheck — translation table generated by make_lang.py from lang.tsv (ru → en, es). Do not edit.\n')
        f.write('#ifndef GTACHECK_LANG_DATA_H\n#define GTACHECK_LANG_DATA_H\n')
        f.write('static const char *const LANG_TABLE[][3] = {\n')
        for ru in order:
            en, es = rows[ru]
            f.write('\t{ %s, %s, %s },\n' % (cstr(ru), cstr(en), cstr(es)))
        f.write('};\nstatic const size_t LANG_TABLE_COUNT = %d;\n#endif\n' % len(order))
    missing = sum(1 for ru in order if not rows[ru][0] or not rows[ru][1])
    print('lang_data.h: %d entries, %d without a complete translation' % (len(order), missing))

def cmd_sync():
    files = sorted(glob.glob(os.path.join(HERE, '*.cpp')))
    keys = extract(files)
    rows, old_order = read_tsv()
    new = [k for k in keys if k not in rows]
    for k in new: rows[k] = ['', '']
    order = keys + [k for k in old_order if k not in set(keys)]   # manual rows (concatenated messages) stay at the end
    write_tsv(order, rows)
    with io.open(KEYS, 'w', encoding='utf-8', newline='\n') as f:
        for i, k in enumerate(order):
            if not rows[k][0] or not rows[k][1]:
                f.write('%d\t%s\n' % (i, esc_tsv(k)))
    print('keys in source: %d, new: %d, needing translation: %d (lang_keys.txt)' % (len(order), len(new), sum(1 for k in order if not rows[k][0] or not rows[k][1])))
    build(order, rows)

def cmd_merge(path, lang):
    col = {'en': 0, 'es': 1}[lang]
    rows, order = read_tsv()
    n = 0; bad = 0
    for line in io.open(path, encoding='utf-8'):
        line = line.rstrip('\n')
        if not line.strip(): continue
        m = re.match(r'^(\d+)\t(.*)$', line)
        if not m: bad += 1; continue
        i = int(m.group(1))
        if i >= len(order): bad += 1; continue
        rows[order[i]][col] = unesc_tsv(m.group(2)); n += 1
    write_tsv(order, rows)
    print('merged %d %s translations (%d bad lines)' % (n, lang, bad))
    build(order, rows)

if __name__ == '__main__':
    a = sys.argv[1:]
    if not a or a[0] == 'sync': cmd_sync()
    elif a[0] == 'merge': cmd_merge(a[1], a[2])
    elif a[0] == 'build':
        rows, order = read_tsv(); build(order, rows)
